//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nist_rand_entry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chain_index: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub pulse_index: i64,
    pub uri: String,
    pub timestamp: String,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub output_value: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
